# Final Project Proposal

## 1. Research Question

Does the draft position of a NBA player affect their WinShares? How do lottery picks (1-14) affect WinShares compared with non-lottery picks? Does being a first-round pick increase or decrease WinShares? Additionally, what factors are attributable to a player having a high WinShare?

## 2. Justification - why is this relevant to you or industry?

NBA teams that "tank" the regular season in order to get a high draft pick has been an ongoing topic of discussion. "Tanking" means purposefully not trying your best to win games in order to increase the odds of winning the NBA Draft lottery and obtaining the 1st pick in the draft. The rationale for this strategy is that players picked 1st helps the future prospects of the team's future when it comes to winning. While only 1 team can win the lottery, having a draft lottery pick that is from 2 and 14 is thought to help increase the future aspirations of teams who haven't had luck winning games. By exploring this dataset, I hope to uncover any findings that may indicate whether or not this strategy of "tanking" is worthwhile.

## 3. Data Sources - did you find this data online or collect yourself? Provide links

I found this dataset on Kaggle:
https://www.kaggle.com/datasets/benwieland/nba-draft-data

## 4. Libraries potentially being used

* Pandas Library: Pandas will be used to import the csv file that contains the data and store it in a variable, as well as performing data manipulation, exploration, and cleaning.
* NumPy Library: NumPy will be used for conducting any mathematical operation on numeric columns that can help provide any insight in why players have high WinShares. Additionally, I would like to use this library to create conditional values that can help narrow down specific players that have high WinShares.
* Matplotlib/Seaborn Libraries: I would use one of these two libraries to visualize my findings. I'm unsure yet which library to use.

## 5. EDA and summary statistics

When exploring the initial statistics of the data, there seems to be multiple columns that have missing data. There are two columns that have the same values (Rk and Pk), so I will drop one of them. Multiple column names are abbreviated, so for the sake of clarity I want to rename some of the columns. The mean of WinShares(WS) in the data is 17.57. There appears to be some outliers in the WS column, with the max value in WS being 248.3 and the IQR between 0.4 and 23.8. I will keep this in mind as I explore the data further.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/moham6839/Data602_Assignment7/main/draft-data-20-years.csv")

In [3]:
df

,Unnamed: 0,Rk,Pk,Tm,Player,College,Yrs,G,TOTMP,TOTPTS,...,WS/48,BPM,VORP,DraftYr,MPG,PPG,RPG,APG,playerurl,DraftYear
0,1,1,1,BRK,Derrick Coleman,Syracuse,15.0,781.0,25903.0,12884.0,...,0.119,1.4,22.3,1990,33.2,16.5,9.3,2.5,https://www.sports-reference.com/cbb/players/d...,1990
1,2,2,2,OKC,Gary Payton,Oregon State,17.0,1335.0,47117.0,21813.0,...,0.148,3.3,62.5,1990,35.3,16.3,3.9,6.7,https://www.sports-reference.com/cbb/players/g...,1990
2,3,3,3,DEN,Mahmoud Abdul-Rauf,LSU,9.0,586.0,15628.0,8553.0,...,0.077,-0.8,4.5,1990,26.7,14.6,1.9,3.5,https://www.sports-reference.com/cbb/players/m...,1990
3,4,4,4,ORL,Dennis Scott,Georgia Tech,10.0,629.0,17983.0,8094.0,...,0.089,0.2,9.9,1990,28.6,12.9,2.8,2.1,https://www.sports-reference.com/cbb/players/d...,1990
4,5,5,5,CHA,Kendall Gill,Illinois,15.0,966.0,29481.0,12914.0,...,0.078,0.1,15.8,1990,30.5,13.4,4.1,3.0,https://www.sports-reference.com/cbb/players/k...,1990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1863,1864,56,56,CHA,Scottie Lewis,Florida,1.0,2.0,7.0,1.0,...,0.164,6.1,0.0,2021,3.5,0.5,0.0,0.5,https://www.sports-reference.com/cbb/players/s...,2021
1864,1865,57,57,CHA,Balša Koprivica,Florida State,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2021,NaN,NaN,NaN,NaN,https://www.sports-reference.com/cbb/players/b...,2021
1865,1866,58,58,NYK,Jericho Sims,Texas,1.0,18.0,117.0,19.0,...,0.145,-0.6,0.0,2021,6.5,1.1,1.5,0.1,https://www.sports-reference.com/cbb/players/j...,2021
1866,1867,59,59,BRK,RaiQuan Gray,Florida State,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2021,NaN,NaN,NaN,NaN,https://www.sports-reference.com/cbb/players/r...,2021
1867,1868,60,60,IND,Georgios Kalaitzakis,NaN,1.0,9.0,48.0,16.0,...,-0.005,-8.0,-0.1,2021,5.3,1.8,0.9,0.0,NaN,2021

In [4]:
df.describe()

,Unnamed: 0,Rk,Pk,Yrs,G,TOTMP,TOTPTS,TOTTRB,TOTAST,FG%,...,WS,WS/48,BPM,VORP,DraftYr,MPG,PPG,RPG,APG,DraftYear
count,1868.00000,1868.000000,1868.000000,1621.000000,1621.000000,1621.000000,1621.000000,1621.000000,1621.000000,1616.000000,...,1621.000000,1620.000000,1620.000000,1621.000000,1868.000000,1621.000000,1621.000000,1621.000000,1621.000000,1868.000000
mean,934.50000,29.758030,29.758030,6.305367,342.477483,8250.098705,3511.962369,1477.016656,754.235657,0.435562,...,17.576373,0.061087,-2.333457,4.318816,2005.789079,18.040592,7.218692,3.186243,1.531215,2005.789079
std,539.38947,16.945052,16.945052,4.640924,322.947374,9765.177283,4788.948725,1993.300685,1266.295204,0.084803,...,27.862566,0.096265,4.165910,11.404481,9.170436,8.730546,4.970593,2.091627,1.472497,9.170436
min,1.00000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1.900000,-1.264000,-52.000000,-8.500000,1990.000000,0.000000,0.000000,0.000000,0.000000,1990.000000
25%,467.75000,15.000000,15.000000,2.000000,69.000000,792.000000,253.000000,123.000000,43.000000,0.403000,...,0.400000,0.030000,-3.900000,-0.400000,1998.000000,10.800000,3.300000,1.700000,0.500000,1998.000000
50%,934.50000,30.000000,30.000000,5.000000,230.000000,4000.000000,1516.000000,635.000000,250.000000,0.435000,...,4.900000,0.069000,-2.000000,0.000000,2006.000000,17.600000,6.100000,2.800000,1.000000,2006.000000
75%,1401.25000,44.000000,44.000000,10.000000,575.000000,13026.000000,5081.000000,2093.000000,896.000000,0.473000,...,23.800000,0.103000,-0.300000,4.300000,2014.000000,24.900000,9.900000,4.200000,2.000000,2014.000000
max,1868.00000,60.000000,60.000000,22.000000,1541.000000,51563.000000,36559.000000,15091.000000,12091.000000,1.000000,...,248.300000,1.442000,51.100000,141.400000,2021.000000,41.100000,27.100000,13.400000,9.500000,2021.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1868 entries, 0 to 1867
Data columns (total 26 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1868 non-null   int64
 1   Rk          1868 non-null   int64
 2   Pk          1868 non-null   int64
 3   Tm          1868 non-null   object
 4   Player      1868 non-null   object
 5   College     1533 non-null   object
 6   Yrs         1621 non-null   float64
 7   G           1621 non-null   float64
 8   TOTMP       1621 non-null   float64
 9   TOTPTS      1621 non-null   float64
 10  TOTTRB      1621 non-null   float64
 11  TOTAST      1621 non-null   float64
 12  FG%         1616 non-null   float64
 13  3P%         1500 non-null   float64
 14  FT%         1584 non-null   float64
 15  WS          1621 non-null   float64
 16  WS/48       1620 non-null   float64
 17  BPM         1620 non-null   float64
 18  VORP        1621 non-null   float64
 19  DraftYr     1868 non-null   int64
 20  MPG         1621 non-null   float64
 21  PPG         1621 non-null   float64
 22  RPG         1621 non-null   float64
 23  APG         1621 non-null   float64
 24  playerurl   1533 non-null   object
 25  DraftYear   1868 non-null   int64
dtypes: float64(17), int64(5), object(4)
memory usage: 379.6+ KB

In [6]:
df["WS"].mean()

17.576372609500307